version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
     # - ./backend/config.yml:/app/config.yml
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - mongo
  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data_container:/data/db
  
volumes:
  mongodb_data_container: